# Generated by Django 3.2.7 on 2021-09-28 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_app', '0003_table_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='distance',
            field=models.FloatField(blank=True, null=True, verbose_name='Расстояние'),
        ),
    ]
